// PHAGENTIC component logic. Factory called from the 1-line data-dc-script in index.html
// (index.html is generated by build.js from src/shell.html + src/widgets/*.html).
window.PhagenticComponent = function(DCLogic, StreamableLogic, React){
return class Component extends DCLogic {
  constructor(props){
    super(props);
    this._chatLen=0;
    this.phage=this.buildPhage(92);
    this.runPalette=['#6f8466','#847ea6','#94762f','#6f8499','#b06a45','#7f9a72'];
    // A muted "spectrum" in the same earthy/glassy vibe as the run palette — low
    // saturation, mid lightness — so any picked colour fits the site.
    this.huePalette=(()=>{ const a=[]; for(let h=0; h<360; h+=24) a.push(this.hslToHex(h, 0.34, 0.55)); return a; })();
    const calcLayout=[['√','fn'],['x²','fn'],['1/x','fn'],['÷','op'],['7','n'],['8','n'],['9','n'],['×','op'],['4','n'],['5','n'],['6','n'],['−','op'],['1','n'],['2','n'],['3','n'],['+','op'],['0','n'],['.','n'],['±','fn'],['=','eq']];
    this.calcKeys=calcLayout.map(([l,type])=>{
      const bg=type==='eq'?'#6f8466':type==='op'?'rgba(148,118,47,.12)':type==='fn'?'rgba(59,55,47,.06)':'rgba(255,255,255,.36)';
      const c=type==='eq'?'#fbf8f2':type==='op'?'#94762f':type==='fn'?'rgba(46,43,36,.7)':'#2e2b24';
      return { l, c, bg, h:()=>this.calcInput(l) };
    });
    // Named equations for the Blue Bottle reaction. Each opens in a roomy detail
    // view with labelled, unit-tagged inputs. `temp` is a two-way °C⇄°F converter.
    this.eqLib=[
      {id:'amp', name:'Oscillation amplitude', expr:'A = peak − trough', desc:'Peak-to-trough swing of the normalized blue signal — the controller keeps this above ~0.4.', fields:[['Peak','P','B̂ 0–1'],['Trough','T','B̂ 0–1']], fn:v=>v.P-v.T, unit:'B̂', dp:2},
      {id:'period', name:'Oscillation period', expr:'T = 2 × t½', desc:'Time for one full blue → colorless → blue cycle.', fields:[['Half-period','H','s']], fn:v=>2*v.H, unit:'s', dp:1},
      {id:'freq', name:'Frequency', expr:'f = 1 ÷ T', desc:'Oscillations per second.', fields:[['Period','P','s']], fn:v=>v.P?1/v.P:0, unit:'Hz', dp:4},
      {id:'blue', name:'Blue intensity', expr:'B̂ = (b − r) ÷ 255', desc:'Normalized blueness from the TCS34725 colour sensor.', fields:[['Blue channel','b','0–255'],['Red channel','r','0–255']], fn:v=>(v.b-v.r)/255, unit:'B̂', dp:3},
      {id:'stir', name:'Stirrer → half-period', expr:'t½ = (60 − 44·s) ÷ 2', desc:'Model estimate: more stirring adds O₂ faster and shortens the blue phase. s = PWM ÷ 255.', fields:[['Stirrer','s','PWM 0–255']], fn:v=>{const x=Math.max(0,Math.min(1,v.s/255));return (60-44*x)/2;}, unit:'s', dp:1},
      {id:'kla', name:'O₂ transfer rate', expr:'OTR = kLa · (C*−C)', desc:'Oxygen mass transfer — drives the oxidized (blue) phase.', fields:[['kLa','k','1/s'],['C*−C','d','mg/L']], fn:v=>v.k*v.d, unit:'mg/L·s', dp:3},
      {id:'dose', name:'Glucose dose volume', expr:'V = q · t', desc:'Bolus volume delivered by one pump pulse.', fields:[['Flow rate','q','mL/s'],['Pulse time','t','s']], fn:v=>v.q*v.t, unit:'mL', dp:2},
      {id:'cycles', name:'Cycles per run', expr:'N = (R·60) ÷ T', desc:'How many oscillations fit a run of a given length.', fields:[['Run length','R','min'],['Period','P','s']], fn:v=>v.P?(v.R*60)/v.P:0, unit:'cycles', dp:0},
      {id:'phage', name:'Phage ⇄ blue', expr:'S = 10·log₁₀(P+1) ÷ 12', desc:'Map bacteriophage count to a blue-bottle shade on a 0–10 slider. Clear (0.00) is a sterile sample; deepest blue (10.00) is a saturated culture at ~10¹² phages. Drag the slider or type a count — both stay in sync. Inverse: P = 10^(1.2·S) − 1.', phageConv:true},
      {id:'temp', name:'Temperature  °C ⇄ °F', expr:'°F = °C·9/5 + 32', desc:'Convert between Celsius and Fahrenheit — type in either box.', converter:true},
    ];
    this.panelIds=['swatch','world','narr','manual','calc','ask','runs','notes','actuators'];
    this.labels={swatch:'COLOUR LOG', world:'OSCILLATION', narr:'NARRATION', manual:'CONSOLE', calc:'CALCULATOR', ask:'ASK PHAGE', runs:'RUNS', notes:'TEMP NOTES', actuators:'ACTUATORS'};
    // starting size per panel (px, design space); user-resizable from the corner.
    this._size={ swatch:[350,460], world:[620,420], narr:[360,420], manual:[490,350], calc:[360,430], ask:[400,420], runs:[350,400], notes:[340,420], actuators:[360,300] };
    this.dragH={}; this.closeH={}; this.openH={}; this.resizeH={};
    this.panelIds.forEach(id=>{ this.dragH[id]=this.startDrag(id); this.closeH[id]=()=>this.closePanel(id); this.openH[id]=()=>this.openPanel(id); this.resizeH[id]=this.startResize(id); });
    this.knobCool=this.startKnob('stirrer',0,255); this.knobMoi=this.startKnob('glucoseDoseMs',50,2000); this.knobThr=this.startKnob('ampThreshold',5,95); this.knobLight=this.startKnob('light',0,255);
    this._zc=this.panelIds.length;
    const mk=(open,id)=>({x:20,y:20,w:this._size[id][0],h:this._size[id][1],open, zi:this.panelIds.indexOf(id)+1});
    this._be=null; this._ble=null; this._bleName='Bioreactor';
    // Mirrors hub/config.json — used to configure pins when connecting directly over BLE.
    this._defaultConfig={ mosfets:[{name:'Glucose Pump',pin:18,mode:'digital'},{name:'NaOH Pump',pin:19,mode:'digital'},{name:'Stirrer',pin:23,mode:'pwm'}], sensor_light:{pin:25} };
    this._pins=this.pinsFromConfig(this._defaultConfig);   // sets this._pins + this._names from config
    this.state={
      onLanding:true, running:true, mode:'auto', cycling:false, bumped:false, uiZoom:1.0, live:false,
      // setpoints (UI-owned; the in-browser control loop reads these)
      stirrer:150, glucoseDoseMs:500, ampThreshold:40, targetHalfPeriod:25, solveMode:'period', light:255, calibTxt:'', source:'off',
      targetBlue:0.7, targetTime:25, targetPhage:'251188642',   // targetTime = cycle period (s); phage count for targetBlue 0.7 (= 10^(12·0.7)−1)
      glucoseOn:false, naohOn:false,
      settingsOpen:false, bleName:'Bioreactor', bleStatus:'', bleKnown:0,
      // measured / derived (flushed from the ingest loop ~10Hz)
      runName:'Run 01', runColor:'#6f8466', colorOpen:false, hint:'', hintX:0, hintY:0,
      t:0, runIndex:1, blue:0.5, rgb:[228,226,214], lux:0,
      amp:0, period:0, halfPeriod:0, phase:'colorless', blueEst:0.5, ampEst:0, phaseEst:'colorless', cycles:0, stallRisk:0,
      stirrerOut:150, lightOut:255, glucoseActive:false, naohActive:false, glucosePulses:0, lastPulseT:null,
      hist:[],
      narr:[{txt:'System online. Awaiting first blue↔colorless swing.', kind:'info'}],
      panels:{ swatch:mk(true,'swatch'), world:mk(true,'world'), narr:mk(true,'narr'), manual:mk(true,'manual'), calc:mk(false,'calc'), ask:mk(true,'ask'), runs:mk(true,'runs'), notes:mk(false,'notes'), actuators:mk(true,'actuators') },
      drag:null, resize:null, stageW:1304, stageH:740,
      calc:{display:'0', acc:null, op:null, fresh:true}, calcTab:'keys',
      eq:{ amp:{}, period:{}, freq:{}, blue:{}, stir:{}, kla:{}, dose:{}, cycles:{}, temp:{}, phage:{s:'5.00', p:'999999'} }, eqSel:null,
      chat:[{role:'sys', text:'Ask me about this run — amplitude, period, stalling, or how to drive the oscillation.'}], chatInput:'',
      runs:[],
      captures:[], compareMode:false, compareSel:[], animating:false,
      notes:[{title:'Note 1', body:''}], noteIdx:0,
      landW:1320, landH:760,
      bodies:[
        {id:'hero', x:920, y:300, vx:0.45, vy:0.35, scale:1.23, kind:'full', spin:21},
      ],
    };
    this.resetProc(0);
  }
  componentDidMount(){ this.resetProc(this.now()); this.flushT=setInterval(()=>this.flush(),100); this.land=setInterval(()=>this.landingTick(),32); this._onResize=()=>{ this.measure(); this.measureLanding(); }; window.addEventListener('resize',this._onResize); requestAnimationFrame(()=>{ this.measure(); this.measureLanding(); }); setTimeout(()=>{ this.measure(); this.measureLanding(); },140); this.connectBackend(); if(/console/.test(location.hash)||new URLSearchParams(location.search).get('view')==='console'){ setTimeout(()=>this.enter(),220); } }
  componentWillUnmount(){ clearInterval(this.flushT); clearInterval(this.land); window.removeEventListener('resize',this._onResize); if(this._be) this._be.close(); }
  goHome=()=>{ this.setState({ onLanding:true }, ()=>this.measureLanding()); };

  // ---- headless backend bridge -----------------------------------------------
  // The backend (backend/, FastAPI on :8080) owns the device link, oscillation
  // analysis, the control loop and the pluggable ML model. This UI is a thin
  // client: it renders the streamed state and sends commands back over one
  // WebSocket. No analysis, control, or simulation runs in the browser.
  now(){ return Date.now()/1000; }
  connectBackend(){
    const be=window.PhagenticBackend; if(!be) return; this._be=be;
    be.onConfig=(cfg)=>this.resolvePins(cfg);
    be.onStatus=(up)=>{
      this.setState({ live:up });
      this.pushNarr(up?'Backend connected.':'Backend offline — reconnecting…', up?'win':'dim');
    };
    be.onState=(m)=>this.applyState(m);
    be.connect();
  }
  // Resolve which pin each role lives on FROM THE CONFIG, by device name — so the
  // UI follows the actual hardware wiring (pins can move in config.json). Also
  // captures the real display names so the controls read like the bioreactor.
  pinsFromConfig(cfg){
    const p={stirrer:23, glucose:18, naoh:19, light:25};
    const nm={stirrer:'Stirrer', glucose:'Glucose Pump', naoh:'NaOH Pump', light:'Sensor Light'};
    (cfg.mosfets||[]).forEach(m=>{ const n=(m.name||'').toLowerCase(); if(/stir/.test(n)){ p.stirrer=m.pin; nm.stirrer=m.name; } else if(/gluc/.test(n)){ p.glucose=m.pin; nm.glucose=m.name; } else if(/na.?oh|chlor/.test(n)){ p.naoh=m.pin; nm.naoh=m.name; } });
    if(cfg.sensor_light&&cfg.sensor_light.pin!=null){ p.light=cfg.sensor_light.pin; if(cfg.sensor_light.name) nm.light=cfg.sensor_light.name; }
    this._names=nm;
    return p;
  }
  resolvePins(cfg){ this._pins=this.pinsFromConfig(cfg); }
  pinMap(cfg){ const pins=(cfg.mosfets||[]).map(m=>({pin:m.pin, mode:m.mode})); if(cfg.sensor_light&&cfg.sensor_light.pin!=null) pins.push({pin:cfg.sensor_light.pin, mode:'pwm'}); return pins; }
  // Actuator command → backend (role-based; the backend maps roles to pins).
  cmdSet(cmd,role,value){ if(!this._be) return; if(cmd==='set_pwm') this._be.setActuator(role, Math.round(value)); else this._be.setActuator(role, !!value); }

  // ---- backend connection controls (header button + settings) ---------------
  bleConnect=()=>{ if(!this._be) return; this._be.close(); this._be.connect(); this.pushNarr('Reconnecting to backend…','info'); };
  bleReconnect=()=>this.bleConnect();
  bleDisconnect=()=>{ if(this._be) this._be.close(); this.setState({ live:false }); };
  openSettings=()=>this.setState({settingsOpen:true});
  closeSettings=()=>this.setState({settingsOpen:false});
  setBleName=(e)=>this.setState({bleName:e.target.value});

  // ---- signal helpers --------------------------------------------------------
  hslToHex(h,s,l){ const a=s*Math.min(l,1-l); const f=n=>{ const k=(n+h/30)%12; const c=l-a*Math.max(-1,Math.min(k-3,9-k,1)); return Math.round(c*255).toString(16).padStart(2,'0'); }; return '#'+f(0)+f(8)+f(4); }
  hexToRgba(hex,al){ const h=(hex||'#6f8466').replace('#',''); const n=parseInt(h.length===3?h.replace(/(.)/g,'$1$1'):h,16); return 'rgba('+((n>>16)&255)+','+((n>>8)&255)+','+(n&255)+','+al+')'; }
  blueFromRgb(r,g,b,c){ return Math.max(0,Math.min(1,(b-r)/200)); }   // (b−r): ~0 colorless, large when blue
  rgbForBlue(blue){ const pale=[228,226,214], deep=[38,92,200], tt=Math.max(0,Math.min(1,blue)); return [Math.round(pale[0]+(deep[0]-pale[0])*tt),Math.round(pale[1]+(deep[1]-pale[1])*tt),Math.round(pale[2]+(deep[2]-pale[2])*tt)]; }
  pushNarr(txt,kind){ this._narr.push({txt,kind}); if(this._narr.length>60) this._narr=this._narr.slice(-60); }
  sayOnce(k,txt,kind){ if(!this._said.has(k)){ this._said.add(k); this.pushNarr(txt,kind); } }

  // ---- process state ---------------------------------------------------------
  resetProc(now){
    this._t0=now; this._said=new Set();
    this._blue=0.5; this._rgb=[228,226,214]; this._lux=0;
    this._prevBlue=0.5; this._dir=0; this._lastMax=0.5; this._lastMin=0.5; this._extT=[];
    this._amp=0; this._period=0; this._halfP=0; this._cycles=0; this._phase='colorless'; this._lastExtremeT=0;
    this._blueEst=0.5; this._ampEst=0; this._phaseEst='colorless';
    this._piI=0; this._lowAmp=0; this._lastCycleSeen=0; this._sendAcc=0;
    this._stirrerOut=(this.state&&this.state.stirrer)||150; this._lightOut=(this.state&&this.state.light)||255; this._glucoseActive=false; this._naohActive=false; this._glucosePulses=0; this._lastPulseT=null; this._pulseUntil=0; this._naohUntil=0;
    this._hist=[]; this._narr=[{txt:'System online. Awaiting first blue↔colorless swing.', kind:'info'}];
    this._runs=this._runs||[]; this._sim={phase:0, glucose:1, alk:1, last:null}; this._bump=false;
  }

  // ---- backend state ingest --------------------------------------------------
  // The backend streams the full derived reaction state; we mirror it into
  // instance fields (flush() copies them to React state ~10Hz) and build the
  // rolling waveform + narration locally. No analysis or control runs here.
  applyState(m){
    this._t=m.t; this._blue=m.blue; if(m.rgb) this._rgb=m.rgb.slice(); this._lux=m.lux;
    this._amp=m.amp; this._period=m.period; this._halfP=m.half_period; this._phase=m.phase;
    this._blueEst=(m.blue_est!=null?m.blue_est:m.blue); this._ampEst=(m.amp_est!=null?m.amp_est:m.amp); this._phaseEst=m.phase_est||m.phase;
    this._cycles=m.cycles; this._stallRisk=m.stall_risk;
    this._stirrerOut=m.stirrer_out; this._lightOut=m.light_out;
    this._glucoseActive=!!m.glucose_active; this._naohActive=!!m.naoh_active;
    this._glucosePulses=m.glucose_pulses; this._lastPulseT=m.last_pulse_t;
    this._mode=m.mode; this._modelName=m.model_name; this._modelParams=m.model_params||{}; this._modelError=!!m.model_error;
    this._ble=m.ble;
    if(this.state.running){ this._hist.push({t:+(m.t||0).toFixed(2), blue:+(m.blue||0).toFixed(4), blueEst:+(this._blueEst||0).toFixed(4), mid:0.5}); if(this._hist.length>600) this._hist.shift(); }
    if(this._cycles>=1) this.sayOnce('first','First full cycle complete — oscillation established.','win');
    if(this._amp>=0.6) this.sayOnce('strong','Strong swing — amplitude '+this._amp.toFixed(2)+'.','info');
    (m.narr_new||[]).forEach(n=>this.pushNarr(n.txt, n.kind));
  }

  // ---- device control → backend commands (role-based) ------------------------
  // Hard ON/OFF hold for a digital pump. The backend holds it until told otherwise.
  setDigitalOut(role,on){ if(this._be) this._be.setActuator(role, !!on); this.setState({ mode:'manual', [role+'On']:on }); this.pushNarr((this._names[role]||role)+(on?' — ON (held)':' — OFF'), on?'warn':'info'); }
  // Momentary pulse — the backend owns the timer and turns the pump back off.
  pulseDigital(role){
    const ms=(role==='glucose'?Math.round(this.state.glucoseDoseMs):1000);
    if(this._be) this._be.pulseActuator(role, ms);
    this.pushNarr('pulse '+(this._names[role]||role)+' · '+ms+' ms', 'warn');
  }
  runColor(n){ return this.runPalette[(n-1)%this.runPalette.length]; }
  resetRun(now,log,note){
    if(log){ this._runs.push({n:this.state.runIndex, name:this.state.runName, cycles:this._cycles, color:this.state.runColor}); this._runs=this._runs.slice(-30); }
    this.resetProc(now);
    if(this._be) this._be.resetRun();
    this.setState(s=>{ const n=log?s.runIndex+1:s.runIndex; return { runIndex:n, runName:log?('Run '+String(n).padStart(2,'0')):s.runName }; });
    if(note) this.pushNarr(note,'info');
  }
  setRunName=(e)=>this.setState({ runName:e.target.value });
  openColor=()=>this.setState(s=>({ colorOpen:!s.colorOpen }));
  pickRunColor=(hex)=>this.setState({ runColor:hex, colorOpen:false });
  deleteRun(i){ if(i>=0&&i<this._runs.length){ this._runs.splice(i,1); this.flush(); } }
  // glassy hover hints for the header buttons
  // Show the hint directly under the hovered control (captures its position).
  setHint=(t)=>(e)=>{ const el=e&&e.currentTarget, r=el&&el.getBoundingClientRect?el.getBoundingClientRect():null; this.setState({ hint:t, hintX:r?(r.left+r.width/2):0, hintY:r?(r.bottom+8):0 }); };
  clearHint=()=>this.setState({ hint:'' });
  // Copy fast-changing instance fields into React state (~10Hz) so the sensor rate
  // is decoupled from render cost.
  flush(){
    // device/bluetooth status comes straight from the backend's `ble` field.
    const b=this._ble; const src=(b===true||(typeof b==='string'&&/conn|on|ready|live|true/i.test(b)))?'hub':'off';
    // state.mode is the UI view (auto / manual) and is user-owned — set only by the
    // AUTO/MANUAL toggle and LAUNCH. We deliberately do NOT sync it from the backend
    // mode here, so live state frames can't flip the view or hide the auto panel.
    this.setState({ t:this._t||0, blue:this._blue, rgb:this._rgb.slice(), lux:this._lux, amp:this._amp, period:this._period, halfPeriod:this._halfP, phase:this._phase, blueEst:this._blueEst, ampEst:this._ampEst, phaseEst:this._phaseEst, cycles:this._cycles, stallRisk:this._stallRisk||0, stirrerOut:this._stirrerOut, lightOut:this._lightOut, glucoseActive:this._glucoseActive, naohActive:this._naohActive, glucosePulses:this._glucosePulses, lastPulseT:this._lastPulseT, hist:this._hist.slice(), narr:this._narr.slice(), runs:this._runs.slice(), source:src });
  }
  componentDidUpdate(){
    if(!this._chatEl) return;
    const last=this.state.chat[this.state.chat.length-1];
    // Scroll on a new message, or while the last reply is still streaming in.
    if(this.state.chat.length!==this._chatLen || (last&&last.streaming)){
      this._chatLen=this.state.chat.length;
      this._chatEl.scrollTop=this._chatEl.scrollHeight;
    }
  }

  // Shelf / best-fit packing: lay open panels left→right in panelIds order,
  // wrapping to a new row when the next would overflow the desk width. This is
  // the "puzzle" tidy — it adapts to each panel's current size.
  // ---- 3D phage model (home-screen floaters) --------------------------------
  seg(A,B){
    const dx=B[0]-A[0], dy=B[1]-A[1], dz=B[2]-A[2], len=Math.hypot(dx,dy,dz);
    const yaw=Math.atan2(dy,dx)*180/Math.PI, pit=Math.atan2(dz,Math.hypot(dx,dy))*180/Math.PI;
    return { w:len.toFixed(1)+'px', sw:len.toFixed(1)+'px', t:`translate3d(${A[0].toFixed(1)}px,${A[1].toFixed(1)}px,${A[2].toFixed(1)}px) rotateZ(${yaw.toFixed(2)}deg) rotateY(${(-pit).toFixed(2)}deg)` };
  }
  buildPhage(S){
    const TAU=Math.PI/3;
    const hexRing=(y,r,phase)=>{ const a=[]; for(let i=0;i<6;i++){ const ang=i*TAU+(phase||0); a.push([Math.cos(ang)*r, y, Math.sin(ang)*r]); } return a; };
    const Req=S*0.92, Rbelt=S*0.80, cap=S*0.74, midH=S*1.18;
    const yA=-(midH/2+cap), yT=-midH/2, yEq=0, yB=midH/2, yN=midH/2+cap;
    const ringT=hexRing(yT,Rbelt), ringEq=hexRing(yEq,Req,TAU/2), ringB=hexRing(yB,Rbelt);
    const Apex=[0,yA,0], Neck=[0,yN,0];
    const rTail=S*0.26, tailLen=S*1.9, bpY=yN+tailLen, rBp=S*0.42;
    const ringN=hexRing(yN,rTail,TAU/2), ringP=hexRing(bpY,rTail,TAU/2), bpRing=hexRing(bpY,rBp);
    const ld=[0.42,-0.5,0.76], ll=Math.hypot(ld[0],ld[1],ld[2]), L=[ld[0]/ll,ld[1]/ll,ld[2]/ll];
    const faces=[]; const shadeAt=(nn)=>Math.max(0,Math.min(1,(nn[0]*L[0]+nn[1]*L[1]+nn[2]*L[2]+1)/2));
    const tri=(A,B,C,base,aLo,aHi)=>{
      const u=[B[0]-A[0],B[1]-A[1],B[2]-A[2]], v=[C[0]-A[0],C[1]-A[1],C[2]-A[2]];
      let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];
      const cen=[(A[0]+B[0]+C[0])/3,(A[1]+B[1]+C[1])/3,(A[2]+B[2]+C[2])/3];
      if(n[0]*cen[0]+n[1]*cen[1]+n[2]*cen[2]<0) n=[-n[0],-n[1],-n[2]];
      const nl=Math.hypot(n[0],n[1],n[2])||1, nn=[n[0]/nl,n[1]/nl,n[2]/nl];
      const sh=shadeAt(nn), g=Math.pow(sh,0.8);
      const r=Math.round(base[0]+g*base[3]), gg=Math.round(base[1]+g*base[4]), b=Math.round(base[2]+g*base[5]), a=(aLo+g*(aHi-aLo)).toFixed(2);
      const tf=`matrix3d(${u[0].toFixed(2)},${u[1].toFixed(2)},${u[2].toFixed(2)},0,${v[0].toFixed(2)},${v[1].toFixed(2)},${v[2].toFixed(2)},0,${nn[0].toFixed(3)},${nn[1].toFixed(3)},${nn[2].toFixed(3)},0,${A[0].toFixed(2)},${A[1].toFixed(2)},${A[2].toFixed(2)},1)`;
      faces.push({ tf, bg:`rgba(${r},${gg},${b},${a})`, sh, cen });
    };
    const quad=(A,B,C,D,base,lo,hi)=>{ tri(A,B,C,base,lo,hi); tri(A,C,D,base,lo,hi); };
    const headCol=[96,108,150,140,128,104], tailCol=[110,124,158,118,110,92];
    for(let i=0;i<6;i++){ const j=(i+1)%6;
      tri(Apex,ringT[i],ringT[j],headCol,0.16,0.62);
      quad(ringT[i],ringT[j],ringEq[j],ringEq[i],headCol,0.14,0.58);
      quad(ringEq[i],ringEq[j],ringB[j],ringB[i],headCol,0.14,0.58);
      tri(Neck,ringB[j],ringB[i],headCol,0.16,0.62);
    }
    for(let i=0;i<6;i++){ const j=(i+1)%6;
      quad(ringN[i],ringN[j],ringP[j],ringP[i],tailCol,0.16,0.42);
      tri(ringP[i],ringP[j],bpRing[i],tailCol,0.18,0.46); tri(ringP[j],bpRing[j],bpRing[i],tailCol,0.18,0.46);
    }
    const lines=[]; const edge=(A,B,w,br)=>lines.push({...this.seg(A,B), wgt:(w||1).toFixed(1)+'px', bright:br?1:0});
    for(let i=0;i<6;i++){ const j=(i+1)%6;
      edge(Apex,ringT[i],1.4,1); edge(ringT[i],ringT[j],1.2,1); edge(ringEq[i],ringEq[j],1.5,1);
      edge(ringB[i],ringB[j],1.2,1); edge(Neck,ringB[i],1.4,1);
      edge(ringT[i],ringEq[i],1.1,0); edge(ringEq[i],ringB[i],1.1,0);
    }
    for(let k=0;k<=4;k++){ const rr=hexRing(yN+tailLen*(k/4), rTail, TAU/2); for(let i=0;i<6;i++) edge(rr[i],rr[(i+1)%6],0.9,0); }
    for(let i=0;i<6;i++){ edge(ringN[i],ringP[i],1.0,0); edge(bpRing[i],bpRing[(i+1)%6],1.4,1); }
    const fibers=[]; const feet=[];
    for(let i=0;i<6;i++){ const ang=i*TAU, bx=Math.cos(ang), bz=Math.sin(ang), base=bpRing[i];
      const knee=[base[0]+bx*S*0.86, bpY+S*0.50, base[2]+bz*S*0.86];
      const foot=[knee[0]+bx*S*0.30, knee[1]+S*1.02, knee[2]+bz*S*0.30];
      fibers.push({...this.seg(base,knee), wgt:'2.2px'}); fibers.push({...this.seg(knee,foot), wgt:'1.8px'});
      feet.push({ t:`translate3d(${foot[0].toFixed(1)}px,${foot[1].toFixed(1)}px,${foot[2].toFixed(1)}px)` });
    }
    const lit=faces.filter(f=>f.cen[1]<yEq).slice().sort((a,b)=>b.sh-a.sh).slice(0,3);
    const dots=lit.map(f=>({ t:`translate3d(${f.cen[0].toFixed(1)}px,${f.cen[1].toFixed(1)}px,${f.cen[2].toFixed(1)}px)`, sz:'6px', mg:'-3px', bg:'rgba(255,255,255,.98)', glow:'0 0 10px rgba(255,255,255,.95)' }))
      .concat(feet.map(f=>({ t:f.t, sz:'5px', mg:'-2.5px', bg:'#eef0fb', glow:'0 1px 5px rgba(90,80,120,.4)' })));
    const rS=rBp*2, bpT=`translate3d(${(-rS/2).toFixed(1)}px,${(bpY-rS/2).toFixed(1)}px,${(-rS/2).toFixed(1)}px) rotateX(90deg)`;
    return { lines, faces, fibers, dots, bpT, rS };
  }
  // Bounding insets for a phage body at the given scale, about its capsid-centre
  // anchor: the apex reaches up, the tail + fibres reach far below. Shared by the
  // drift loop and the resize clamp so the whole body always stays on screen.
  phagePads(scale){ return { x:150*scale, top:130*scale, bot:445*scale }; }
  measureLanding(){ if(!this._land) return; const r=this._land.getBoundingClientRect(); if(r.width<60) return; this.setState(s=>{ const W=r.width,H=r.height; const b=s.bodies.map(o=>{ const p=this.phagePads(o.scale); return {...o, x:Math.max(p.x,Math.min(Math.max(p.x,W-p.x),o.x)), y:Math.max(p.top,Math.min(Math.max(p.top,H-p.bot),o.y))}; }); return { landW:W, landH:H, bodies:b }; }); }
  landingRef=(el)=>{ this._land=el; };
  onLandingMove=(e)=>{ if(!this._land) return; const r=this._land.getBoundingClientRect(); this._lm={x:e.clientX-r.left, y:e.clientY-r.top, t:Date.now()}; };
  // Floating physics: gentle drift, speed clamps, wall bounce, and mouse repulsion
  // (cursor pushes nearby phages away — like nudging something in liquid).
  landingTick(){
    if(!this.state.onLanding) return;
    this.setState(s=>{
      const W=s.landW,H=s.landH,m=this._lm&&(Date.now()-this._lm.t<260)?this._lm:null;
      const bodies=s.bodies.map(o=>{
        let {x,y,vx,vy}=o; const sc=o.scale;
        // Insets sized to the phage's real extent about its capsid-centre anchor
        // (apex reaches up, the tail + fibres reach far below) so the whole body
        // bounces inside a snug container and never clips offscreen.
        const p=this.phagePads(sc), padX=p.x, padTop=p.top, padBot=p.bot;
        if(m){ const dx=x-m.x, dy=y-m.y, d=Math.hypot(dx,dy), R=160; if(d<R&&d>0.1){ const f=(R-d)/R*0.5; vx+=dx/d*f; vy+=dy/d*f; } }
        vx+=Math.sin((Date.now()/2200)+x*0.01)*0.008; vy+=Math.cos((Date.now()/2500)+y*0.01)*0.008;
        const sp=Math.hypot(vx,vy), cap=1.1; if(sp>cap){ vx=vx/sp*cap; vy=vy/sp*cap; }
        if(sp<0.18){ const k=0.18/(sp||1); vx*=k; vy*=k; }
        x+=vx*2; y+=vy*2;
        const loX=o.id==='hero'?Math.max(padX,W*0.46):padX, hiX=Math.max(loX,W-padX);
        const loY=padTop, hiY=Math.max(loY,H-padBot);
        if(x<loX){ x=loX; vx=Math.abs(vx); } if(x>hiX){ x=hiX; vx=-Math.abs(vx); }
        if(y<loY){ y=loY; vy=Math.abs(vy)*0.7; } if(y>hiY){ y=hiY; vy=-Math.abs(vy)*0.7; }
        vx*=0.99; vy*=0.99;
        return {...o, x,y,vx,vy};
      });
      return { bodies };
    });
  }
  // Greedy skyline packing: place each panel at the highest (smallest-y), then
  // leftmost, gap-respecting slot that fits the desk width — tallest first so
  // shorter panels fill the gaps. Minimizes total vertical space, no overlap.
  packLayout(panels, contentW, pin){
    const g=14, m=14, right=contentW-m, P={...panels};
    const placed=[]; const pinned=pin||{}; const pinIds=[];
    // RUNS is pinned to the top-right corner and treated as an obstacle so the greedy
    // pack flows the other panels around it — but only in the default layout. When a
    // caller supplies its own anchors (the console view), RUNS just flows like the rest.
    const autoRuns=!pin && P.runs && P.runs.open;
    if(autoRuns){ const rx=Math.max(m, contentW-P.runs.w-m); P.runs={...P.runs, x:rx, y:m}; placed.push({x:rx, y:m, w:P.runs.w, h:P.runs.h}); }
    // Caller-supplied anchors are placed at fixed spots and treated as obstacles, so
    // the rest of the panels greedily flow around them.
    for(const id in pinned){ if(P[id]&&P[id].open){ const px=Math.max(m, Math.min(pinned[id].x, contentW-P[id].w-m)); const py=Math.max(m, pinned[id].y); P[id]={...P[id], x:px, y:py}; placed.push({x:px, y:py, w:P[id].w, h:P[id].h}); pinIds.push(id); } }
    const open=this.panelIds.filter(id=>P[id]&&P[id].open&&!(autoRuns&&id==='runs')&&pinIds.indexOf(id)<0);
    const order=open.slice().sort((a,b)=>(P[b].h-P[a].h)||(P[b].w-P[a].w)||(this.panelIds.indexOf(a)-this.panelIds.indexOf(b)));
    const yAt=(x,w)=>{ let y=m; placed.forEach(r=>{ if(x < r.x+r.w+g-0.01 && x+w > r.x-g+0.01) y=Math.max(y, r.y+r.h+g); }); return y; };
    order.forEach(id=>{ const w=P[id].w, h=P[id].h;
      let xs=[m]; placed.forEach(r=>{ xs.push(r.x); xs.push(r.x+r.w+g); });
      xs=Array.from(new Set(xs)).filter(x=>x>=m && x+w<=right+0.5).sort((a,b)=>a-b);
      if(!xs.length) xs=[m];
      let best=null;
      xs.forEach(x=>{ const y=yAt(x,w); if(!best || y<best.y-0.5 || (Math.abs(y-best.y)<0.5 && x<best.x)) best={x,y}; });
      P[id]={...P[id], x:best.x, y:best.y}; placed.push({x:best.x, y:best.y, w, h});
    });
    return P;
  }
  // Hand-authored *starting* positions for the console view: CONSOLE top-left (it's
  // the main panel), STATE ESTIMATE beside it, ACTUATORS under CONSOLE, COLOUR LOG
  // centred just below. These are only the initial spots — panels stay freely
  // draggable and tidyDesk re-packs them greedily like any other. NARRATION / ASK /
  // RUNS flow greedily around these four.
  consoleLayout(panels, W){
    const g=14, m=14;
    // Reset the CONSOLE to its canonical size so it starts identically every entry,
    // regardless of any earlier resize or mode toggle.
    const P={...panels}; if(P.manual) P.manual={...P.manual, w:this._size.manual[0], h:this._size.manual[1]};
    const wOf=(id,d)=>P[id]?P[id].w:d, hOf=(id,d)=>P[id]?P[id].h:d;
    const cw=wOf('manual',490), ch=hOf('manual',350), ww=wOf('world',620), wh=hOf('world',420), sw=wOf('swatch',350);
    // Too narrow to honour the arrangement → just greedy-pack everything.
    if(W < m+cw+g+ww+m) return this.packLayout(P, W);
    const pin={
      manual:   { x:m,        y:m },                  // CONSOLE — top-left
      world:    { x:m+cw+g,   y:m },                  // STATE ESTIMATE — beside it
      actuators:{ x:m,        y:m+ch+g },             // ACTUATORS — below CONSOLE
      swatch:   { x:(W-sw)/2, y:m+Math.max(ch,wh)+g },// COLOUR LOG — middle, below top row
    };
    return this.packLayout(P, W, pin);
  }
  // tidyDesk cleanup: lay open panels out in neat, top-aligned rows — tallest first so
  // each row's panels share a similar height, and every row centred horizontally. A
  // calmer, more deliberate grid than the tight skyline pack.
  tidyLayout(panels, W){
    const g=14, m=14, avail=Math.max(0, W-2*m);
    const ids=this.panelIds.filter(id=>panels[id]&&panels[id].open);
    ids.sort((a,b)=>(panels[b].h-panels[a].h)||(panels[b].w-panels[a].w)||(this.panelIds.indexOf(a)-this.panelIds.indexOf(b)));
    const rows=[]; let row=[], rw=0;
    ids.forEach(id=>{ const w=panels[id].w; const add=(row.length?g:0)+w; if(row.length && rw+add>avail+0.5){ rows.push(row); row=[]; rw=0; } row.push(id); rw+=(row.length>1?g:0)+w; });
    if(row.length) rows.push(row);
    const P={...panels}; let y=m;
    rows.forEach(r=>{ const totalW=r.reduce((s,id)=>s+panels[id].w,0)+g*(r.length-1); let x=m+Math.max(0,(avail-totalW)/2); let rowH=0;
      r.forEach(id=>{ P[id]={...P[id], x:Math.round(x), y:Math.round(y)}; x+=panels[id].w+g; rowH=Math.max(rowH, panels[id].h); });
      y+=rowH+g; });
    return P;
  }
  deskW(){ if(!this._scroll) return this.state.stageW; const r=this._scroll.getBoundingClientRect(); return r.width/(this.state.uiZoom||1); }
  deskContentH(panels){ let mb=this.state.stageH; for(const id in panels){ const p=panels[id]; if(p.open) mb=Math.max(mb, p.y+p.h); } return mb+14; }
  scheduleAnimEnd(){ clearTimeout(this._animT); this._animT=setTimeout(()=>this.setState({animating:false}),560); }
  measure(){ if(!this._scroll) return; const r=this._scroll.getBoundingClientRect(), z=this.state.uiZoom||1, W=r.width/z, H=r.height/z; if(W<60) return; this.setState({ stageW:W, stageH:H }); }

  // Forward model used for the "predicted outcome" + solver readouts (matches the sim).
  predict(stirrer){ const s=Math.max(0,Math.min(1,stirrer/255)), period=Math.max(6,60-44*s); return { halfP:period/2, period, amp:Math.max(0,Math.min(1,0.35+0.65*s)) }; }
  solve(target,mode){ const period=2*target; let s=Math.max(0,Math.min(1,(60-period)/44)); let stir=Math.round(s*255); if(mode==='stir') stir=Math.max(40,stir-30); const p=this.predict(stir); return { stir, halfP:p.halfP, amp:p.amp }; }

  // Drag a panel by its title bar — window listeners + scroll-aware coords so it
  // keeps tracking even while the desk is scrolled or the cursor leaves the panel.
  // Bring a panel to the top of the stack (and optionally set drag/resize state).
  bringToFront(id, extra){ this.setState(s=>{ const P={...s.panels}; P[id]={...P[id], zi:++this._zc}; return Object.assign({ panels:P }, extra||{}); }); }
  startDrag(id){ return (e)=>{
    e.preventDefault(); const sc=this._scroll.getBoundingClientRect(), z=this.state.uiZoom||1, p=this.state.panels[id];
    const ox=(e.clientX-sc.left+this._scroll.scrollLeft)/z - p.x, oy=(e.clientY-sc.top+this._scroll.scrollTop)/z - p.y;
    this.bringToFront(id, { drag:{id} });
    const move=(ev)=>{ const cw=this.state.stageW, x=(ev.clientX-sc.left+this._scroll.scrollLeft)/z - ox, y=(ev.clientY-sc.top+this._scroll.scrollTop)/z - oy; this.setState(s=>{ const P={...s.panels}, pp={...P[id]}; pp.x=Math.max(6,Math.min(Math.max(6,cw-pp.w-6),x)); pp.y=Math.max(6,y); P[id]=pp; return { panels:P }; }); };
    const up=()=>{ window.removeEventListener('mousemove',move); window.removeEventListener('mouseup',up); document.body.style.userSelect=''; this.setState({ drag:null }); };
    document.body.style.userSelect='none'; window.addEventListener('mousemove',move); window.addEventListener('mouseup',up);
  }; }
  // Resize a panel from its bottom-right corner.
  startResize(id){ return (e)=>{
    e.preventDefault(); e.stopPropagation(); const z=this.state.uiZoom||1, p=this.state.panels[id], sx=e.clientX, sy=e.clientY, sw=p.w, sh=p.h;
    this.bringToFront(id, { resize:{id} });
    const move=(ev)=>{ const w=Math.max(240,sw+(ev.clientX-sx)/z), h=Math.max(170,sh+(ev.clientY-sy)/z); this.setState(s=>{ const P={...s.panels}; P[id]={...P[id], w, h}; return { panels:P }; }); };
    const up=()=>{ window.removeEventListener('mousemove',move); window.removeEventListener('mouseup',up); document.body.style.userSelect=''; this.setState({ resize:null }); };
    document.body.style.userSelect='none'; window.addEventListener('mousemove',move); window.addEventListener('mouseup',up);
  }; }
  // Vertical-drag knob. Uses window listeners so the drag keeps tracking even when
  // the cursor leaves the knob/stage (the old stage-only tracking felt jumpy).
  // Absolute drag-to-position bar: the fill follows the cursor 1:1 (click anywhere
  // jumps there, drag tracks). Much snappier than the old relative-scale knob.
  startKnob(param,min,max){ return (e)=>{
    e.preventDefault(); e.stopPropagation();
    const rect=e.currentTarget.getBoundingClientRect(), round=(param!=='ampThreshold');
    const isActuator=(param==='stirrer'||param==='light');
    if(isActuator) this.setState({ mode:'manual' });
    const apply=(cy)=>{ let f=1-(cy-rect.top)/rect.height; f=Math.max(0,Math.min(1,f)); let v=min+f*(max-min); if(round) v=Math.round(v); this.setState({ [param]:v }); if(param==='stirrer'){ this._stirrerOut=Math.round(v); this.cmdSet('set_pwm','stirrer',this._stirrerOut); } else if(param==='light'){ this.cmdSet('set_pwm','light',Math.round(v)); } else if(param==='glucoseDoseMs'){ if(this._be) this._be.setModelParams({glucose_dose_ms:Math.round(v)}); } else if(param==='ampThreshold'){ if(this._be) this._be.setModelParams({amp_threshold:v/100}); } };
    apply(e.clientY);
    const move=(ev)=>apply(ev.clientY);
    const up=()=>{ window.removeEventListener('mousemove',move); window.removeEventListener('mouseup',up); document.body.style.userSelect=''; };
    document.body.style.userSelect='none';
    window.addEventListener('mousemove',move); window.addEventListener('mouseup',up);
  }; }
  scrollRef=(el)=>{ this._scroll=el; };
  chatRef=(el)=>{ this._chatEl=el; };

  closePanel(id){ const w=this.deskW(); this.setState(s=>{ const P={...s.panels}; P[id]={...P[id], open:false}; return { panels:this.packLayout(P, w), animating:true }; }); this.scheduleAnimEnd(); }
  // Right-edge slot for a panel: the highest y at the right margin that clears any
  // panel already overlapping that column. Used to pop tool panels open on the right.
  rightSlot(panels, id, W){ const g=14, m=14, p=panels[id], x=Math.max(m, W-m-p.w); let y=m;
    for(const k in panels){ const q=panels[k]; if(k===id||!q.open) continue; if(x < q.x+q.w+g-0.01 && x+p.w > q.x-g+0.01) y=Math.max(y, q.y+q.h+g); }
    return { x, y }; }
  openPanel(id){ const w=this.deskW(); this.setState(s=>{ const P={...s.panels}; P[id]={...P[id], open:true};
    // CALCULATOR and TEMP NOTES are tools — open them on the right, stacked below
    // whatever is already there, without reshuffling the rest of the desk.
    if(id==='calc'||id==='notes'){ const pos=this.rightSlot(P, id, w); P[id]={...P[id], x:pos.x, y:pos.y}; return { panels:P, animating:true }; }
    return { panels:this.packLayout(P, w), animating:true }; }); this.scheduleAnimEnd(); }

  enter=()=>{ const w=this.deskW(); this.setState(s=>{ const P={...s.panels}; this.panelIds.forEach(id=>{ if(id!=='calc'&&id!=='notes') P[id]={...P[id], open:true}; }); return { onLanding:false, panels:this.consoleLayout(P, w), animating:true }; }, ()=>this.measure()); this.scheduleAnimEnd(); };
  // Cursor-tracking "shine" — a soft spotlight follows the pointer across the text. Generic:
  // works on any element via e.currentTarget, and saves/restores the original inline style so it
  // also works on gradient text (logo, hero) without clobbering its base gradient.
  shineMove=(e)=>{ const el=e.currentTarget; if(!el) return; if(el.__shineOrig==null) el.__shineOrig=el.style.cssText; const r=el.getBoundingClientRect(); const x=(e.clientX-r.left).toFixed(0), y=(e.clientY-r.top).toFixed(0); el.style.color='transparent'; el.style.backgroundImage='radial-gradient(circle at '+x+'px '+y+'px, #9fb184 0%, #6f8466 45%, #51663f 100%)'; el.style.webkitBackgroundClip='text'; el.style.backgroundClip='text'; };
  shineReset=(e)=>{ const el=e.currentTarget; if(el&&el.__shineOrig!=null){ el.style.cssText=el.__shineOrig; el.__shineOrig=null; } };

  // Gradient-text shine (logo + hero): a soft white highlight layered OVER the base green→purple
  // gradient (so it blends rather than replaces), and fades out smoothly on leave instead of snapping.
  _gradBase='linear-gradient(100deg,#6f8466,#847ea6 52%,#6f8499)';
  _applyGShine(el, a){ el.style.color='transparent'; el.style.backgroundImage='radial-gradient(circle at '+el.__sx+'px '+el.__sy+'px, rgba(255,255,255,'+a+') 0%, rgba(255,255,255,0) 48%), '+this._gradBase; el.style.webkitBackgroundClip='text'; el.style.backgroundClip='text'; }
  gshineMove=(e)=>{ const el=e.currentTarget; if(!el) return; if(el.__shineOrig==null) el.__shineOrig=el.style.cssText; if(el.__shineRAF){ cancelAnimationFrame(el.__shineRAF); el.__shineRAF=null; } const r=el.getBoundingClientRect(); el.__sx=(e.clientX-r.left).toFixed(0); el.__sy=(e.clientY-r.top).toFixed(0); this._applyGShine(el, 0.5); };
  gshineReset=(e)=>{ const el=e.currentTarget; if(!el) return; if(el.__shineRAF) cancelAnimationFrame(el.__shineRAF); const dur=340, start=performance.now(), a0=0.5; const step=(t)=>{ const k=Math.min(1,(t-start)/dur); this._applyGShine(el, a0*(1-k)); if(k<1){ el.__shineRAF=requestAnimationFrame(step); } else { el.__shineRAF=null; if(el.__shineOrig!=null){ el.style.cssText=el.__shineOrig; el.__shineOrig=null; } } }; el.__shineRAF=requestAnimationFrame(step); };
  // logo also clears the hint tooltip on leave
  logoLeave=(e)=>{ this.gshineReset(e); this.clearHint(); };
  // Entering auto is passive — it just shows the goal inputs. The model does not
  // start until LAUNCH (startCycling). Backend stays idle (manual) until then.
  watchRace=()=>{ const w=this.deskW(); this.setState(s=>{ const keep=new Set(['swatch','world','narr','manual','actuators']); const P={...s.panels}; this.panelIds.forEach(id=>{ P[id]={...P[id], open:keep.has(id)}; }); return { onLanding:false, running:true, mode:'auto', panels:this.consoleLayout(P, w), animating:true }; }, ()=>this.measure()); this.scheduleAnimEnd(); };
  // Play / pause. Pause stops the model AND drives every actuator off, after
  // snapshotting their current values; play restores that snapshot and (if the
  // model was running) re-enters 'ml' — the model instance + its goal persist,
  // so we must NOT re-send setModel, which would build a fresh model and wipe the goal.
  toggleRun=()=>{
    const running=!this.state.running;
    if(!running){
      // PAUSE — remember the live actuator state, then turn everything off.
      this._prePause={ stirrer:this.state.stirrer, light:this.state.light, glucoseOn:this.state.glucoseOn, naohOn:this.state.naohOn };
      if(this._be) this._be.setMode('manual');
      this.cmdSet('set_pwm','stirrer',0); this.cmdSet('set_pwm','light',0);
      this.cmdSet('set_digital','glucose',false); this.cmdSet('set_digital','naoh',false);
      this._stirrerOut=0; this._lightOut=0;
      this.setState({ running:false, stirrer:0, light:0, glucoseOn:false, naohOn:false });
      this.pushNarr('⏸ Paused — all outputs off.', 'warn');
    } else {
      // PLAY — restore the snapshot taken at pause, then resume the model if it was running.
      const p=this._prePause||{ stirrer:this.state.stirrer, light:this.state.light, glucoseOn:this.state.glucoseOn, naohOn:this.state.naohOn };
      this.cmdSet('set_pwm','stirrer',p.stirrer); this.cmdSet('set_pwm','light',p.light);
      this.cmdSet('set_digital','glucose',p.glucoseOn); this.cmdSet('set_digital','naoh',p.naohOn);
      this._stirrerOut=Math.round(p.stirrer); this._lightOut=Math.round(p.light);
      if(this._be && this.state.cycling) this._be.setMode('ml');
      this.setState({ running:true, stirrer:p.stirrer, light:p.light, glucoseOn:p.glucoseOn, naohOn:p.naohOn });
      this.pushNarr(this.state.cycling?'▶ Model resumed — outputs restored.':'▶ Resumed — outputs restored.', 'info');
    }
  };
  // The CONSOLE keeps ONE fixed size for both AUTO and MANUAL — toggling the mode no
  // longer resizes it. Sized (in _size.manual) to fit MANUAL's control grid, which is
  // also tall enough to always show AUTO's LAUNCH button. consoleLayout resets it to
  // this size on every entry, so the console starts the same size every time.
  // AUTO is just the view; it does not engage the model (LAUNCH does).
  setAuto=()=>this.setState({ mode:'auto' });
  // MANUAL stops the model and hands you direct control.
  setManual=()=>{ if(this._be) this._be.setMode('manual'); this.setState({ mode:'manual', cycling:false }); };
  zoomIn=()=>this.setState(s=>({ uiZoom:Math.min(1.4,+(s.uiZoom+0.08).toFixed(2)) }), ()=>this.measure());
  zoomOut=()=>this.setState(s=>({ uiZoom:Math.max(0.8,+(s.uiZoom-0.08).toFixed(2)) }), ()=>this.measure());
  zoomReset=()=>this.setState({ uiZoom:1.0 }, ()=>this.measure());
  // Re-pack only the panels that are currently open; leave minimized ones minimized.
  tidyDesk=()=>{ const w=this.deskW(); this.setState(s=>({ panels:this.tidyLayout({...s.panels}, w), animating:true })); this.scheduleAnimEnd(); };
  bump=()=>{ this._bump=true; this.pushNarr('Disturbance injected — controller re-estimating.','warn'); this.setState({ bumped:true }); };
  remelt=()=>this.resetRun(this.now(),true,'Manual restart — new run logged.');
  addRun=()=>{ this.resetRun(this.now(),true,'New run started — previous batch logged.'); const w=this.deskW(); this.setState(s=>{ const P={...s.panels}; P.runs={...P.runs, open:true}; return { panels:this.packLayout(P, w), animating:true }; }); this.scheduleAnimEnd(); };
  // ---- colour capture log ----------------------------------------------------
  captureColor=()=>{ const s=this.state; const snap={ rgb:s.rgb.slice(), color:'rgb('+s.rgb.join(',')+')', blue:Math.round(s.blue*100), amp:Math.round(s.amp*100), period:s.period.toFixed(1), phase:s.phase, cycles:s.cycles, stirrer:Math.round(s.stirrerOut/255*100), t:s.t.toFixed(1), run:s.runIndex }; this.setState(st=>({ captures:[snap, ...st.captures].slice(0,60) })); };
  clearCaptures=()=>this.setState({ captures:[], compareSel:[], compareMode:false });
  // ---- temp notes (in-memory only; cleared on reload) -----------------------
  newNote=()=>this.setState(s=>({ notes:s.notes.concat([{title:'Note '+(s.notes.length+1), body:''}]), noteIdx:s.notes.length }));
  selectNote=(i)=>()=>this.setState({ noteIdx:i });
  setNoteTitle=(e)=>{ const v=e.target.value; this.setState(s=>{ const n=s.notes.slice(); n[s.noteIdx]={...n[s.noteIdx], title:v}; return { notes:n }; }); };
  setNoteBody=(e)=>{ const v=e.target.value; this.setState(s=>{ const n=s.notes.slice(); n[s.noteIdx]={...n[s.noteIdx], body:v}; return { notes:n }; }); };
  deleteNote=(i)=>()=>this.setState(s=>{ if(s.notes.length<=1) return { notes:[{title:'Note 1', body:''}], noteIdx:0 }; const n=s.notes.slice(); n.splice(i,1); return { notes:n, noteIdx:Math.max(0,Math.min(s.noteIdx, n.length-1)) }; });
  toggleCompare=()=>this.setState(s=>({ compareMode:!s.compareMode, compareSel:[] }));
  toggleCompareSel=(i)=>this.setState(s=>{ const has=s.compareSel.indexOf(i); let sel; if(has>=0) sel=s.compareSel.filter(x=>x!==i); else sel=s.compareSel.concat([i]).slice(-3); return { compareSel:sel }; });
  // ---- equation library ------------------------------------------------------
  selectEq=(id)=>this.setState({ eqSel:id });
  eqBack=()=>this.setState({ eqSel:null });
  clearEq=(id)=>this.setState(s=>({ eq:{...s.eq, [id]:{}} }));
  setTempC=(e)=>{ const c=e.target.value, n=parseFloat(c); this.setState(s=>({ eq:{...s.eq, temp:{ c, f:(c===''||isNaN(n))?'':String(Math.round((n*9/5+32)*100)/100)} } })); };
  setTempF=(e)=>{ const f=e.target.value, n=parseFloat(f); this.setState(s=>({ eq:{...s.eq, temp:{ f, c:(f===''||isNaN(n))?'':String(Math.round(((n-32)*5/9)*100)/100)} } })); };
  // ---- phage ⇄ blue converter: 0–10 slider ↔ phage count ↔ clear→blue shade ---
  sliderToPhage(S){ return Math.pow(10, 1.2*S) - 1; }                                          // P = 10^(1.2·S) − 1
  phageToSlider(P){ return 10*Math.log10(P+1)/12; }                                            // S = 10·log₁₀(P+1) ÷ 12
  sliderToRgb(S){ const t=Math.max(0,Math.min(1,S/10)), v=Math.round(255*(1-t)); return [v,v,255]; }  // white → deep blue
  fmtPhageInput(P){ return P<100 ? String(Number(P.toFixed(2))) : String(Math.round(P)); }     // editable field value
  fmtPhagePretty(P){ return P<1 ? '0' : Math.round(P).toLocaleString(); }                       // grouped read-out
  setPhageSlider=(e)=>{ const raw=e.target.value, n=parseFloat(raw); this.setState(s=>{
    if(raw===''||isNaN(n)) return { eq:{...s.eq, phage:{ s:raw, p:'' }} };
    const S=Math.max(0,Math.min(10,n)); return { eq:{...s.eq, phage:{ s:raw, p:this.fmtPhageInput(this.sliderToPhage(S)) }} }; }); };
  setPhageCount=(e)=>{ const raw=e.target.value, n=parseFloat(raw); this.setState(s=>{
    if(raw===''||isNaN(n)||n<0) return { eq:{...s.eq, phage:{ s:'', p:raw }} };
    const S=Math.max(0,Math.min(10, this.phageToSlider(n))); return { eq:{...s.eq, phage:{ s:S.toFixed(2), p:raw }} }; }); };
  manualFire=()=>this.pulseDigital('glucose');
  pulseGlucose=()=>this.pulseDigital('glucose');
  // PWM hard ON (full)/OFF (0)
  setPwmOut=(role,param,v)=>{ const cv=Math.max(0,Math.min(255,Math.round(v))); if(param==='stirrer') this._stirrerOut=cv; this.cmdSet('set_pwm',role,cv); this.setState({ mode:'manual', [param]:cv }); };
  stirSetOn=()=>this.setPwmOut('stirrer','stirrer',255);  stirSetOff=()=>this.setPwmOut('stirrer','stirrer',0);
  lightSetOn=()=>this.setPwmOut('light','light',255);     lightSetOff=()=>this.setPwmOut('light','light',0);
  gluSetOn=()=>this.setDigitalOut('glucose',true);   gluSetOff=()=>this.setDigitalOut('glucose',false);
  naohSetOn=()=>this.setDigitalOut('naoh',true);      naohSetOff=()=>this.setDigitalOut('naoh',false);
  gluToggle=()=>this.setDigitalOut('glucose',!this.state.glucoseOn);
  naohToggle=()=>this.setDigitalOut('naoh',!this.state.naohOn);
  recolorRun(i){ if(i>=0&&i<this._runs.length){ const idx=this.runPalette.indexOf(this._runs[i].color); this._runs[i]={...this._runs[i], color:this.runPalette[(idx+1)%this.runPalette.length]}; this.flush(); } }

  setCool=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const cv=Math.max(0,Math.min(255,Math.round(v))); this._stirrerOut=cv; if(this.state.live) this.cmdSet('set_pwm','stirrer',cv); this.setState({ mode:'manual', stirrer:cv }); } };
  setMoi=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const cv=Math.max(50,Math.min(2000,Math.round(v))); if(this._be) this._be.setModelParams({glucose_dose_ms:cv}); this.setState({ glucoseDoseMs:cv }); } };
  setThr=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const cv=Math.max(5,Math.min(95,Math.round(v))); if(this._be) this._be.setModelParams({amp_threshold:cv/100}); this.setState({ ampThreshold:cv }); } };
  setTarget=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const cv=Math.max(5,Math.min(90,v)); if(this._be) this._be.setModelParams({target_half_period:cv}); this.setState({ targetHalfPeriod:cv }); } };
  // AUTO targets for the RL policy: reach a target blue intensity by a target time.
  // GoalModel params (backend/control/goal_model.py): goal_blue 0..1, ideal_time abs seconds.
  setTargetBlue=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const cv=Math.max(0,Math.min(1,v/100)); if(this._be) this._be.setModelParams({goal_blue:cv}); this.setState({ targetBlue:cv, targetPhage:this.fmtPhageInput(this.sliderToPhage(cv*10)), mode:'auto' }); } };
  // Target colour expressed as a bacteriophage count (same mapping as the calculator's
  // Phage ⇄ blue): targetBlue is the 0–1 blue level, so P = 10^(12·targetBlue) − 1.
  setTargetPhage=(e)=>{ const raw=e.target.value, n=parseFloat(raw); if(raw===''||isNaN(n)||n<0){ this.setState({ targetPhage:raw }); return; } const cv=Math.max(0,Math.min(1, this.phageToSlider(n)/10)); if(this._be) this._be.setModelParams({goal_blue:cv}); this.setState({ targetPhage:raw, targetBlue:cv, mode:'auto' }); };
  // targetTime is the desired full-cycle PERIOD (s) — the heuristic locks the
  // oscillation cadence to it (backend clamps 6..120). Not a one-shot deadline.
  setTargetTime=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const cv=Math.max(6,Math.min(120,v)); if(this._be) this._be.setModelParams({target_period:cv}); this.setState({ targetTime:cv }); } };
  // Launch: engage the goal model, zero the run clock, and commit the goal.
  // ideal_time is absolute seconds since run start, so after the reset it reads
  // as "reach target blue this many seconds from launch".
  startCycling=()=>{ if(this._be){ this._be.setModel('goal_blue'); this._be.setMode('ml'); this._be.resetRun(); this._be.setModelParams({ goal_blue:this.state.targetBlue, target_period:this.state.targetTime }); } this.setState({ mode:'auto', running:true, cycling:true }); this.pushNarr('▶ Launched — cycling at '+this.state.targetTime+'s period.', 'win'); };
  setSolveEq=()=>this.setState({ solveMode:'period' });
  setSolveEnergy=()=>this.setState({ solveMode:'stir' });
  applySolve=()=>{ const b=this.solve(this.state.targetHalfPeriod, this.state.solveMode); this._stirrerOut=b.stir; if(this.state.live) this.cmdSet('set_pwm','stirrer',b.stir); this.setState({ mode:'manual', stirrer:b.stir }); };
  // NaOH / Chloride pump — manual alkalinity top-up (digital pulse, ~1s).
  pulseNaoh=()=>this.pulseDigital('naoh');
  // Sensor light brightness (PWM) — illuminates the vessel for the TCS34725.
  setLight=(e)=>{ const v=parseFloat(e.target.value); if(!isNaN(v)){ const lv=Math.max(0,Math.min(255,Math.round(v))); if(this.state.live) this.cmdSet('set_pwm','light',lv); this.setState({ light:lv }); } };
  // White-balance recalibration on the hub (aim sensor at white first).
  recalibrateSensor=()=>{
    if(!(this._be&&this._be.recalibrate)) { this.pushNarr('No backend connected to recalibrate.','warn'); return; }
    this.pushNarr('Recalibrating sensor white balance — aim at white…','info'); this.setState({calibTxt:'…'});
    this._be.recalibrate().then(d=>{ const ok=d&&d.status==='ok'; this.setState({calibTxt:ok?'calibrated':'calib failed'}); this.pushNarr(ok?('White balance set · R×'+d.wb[0].toFixed(2)+' G×'+d.wb[1].toFixed(2)+' B×'+d.wb[2].toFixed(2)):'Recalibration failed.', ok?'win':'warn'); }).catch(()=>{ this.setState({calibTxt:'failed'}); });
  };
  reloadCfg=()=>{ if(this._be){ this._be.reloadConfig(); this.pushNarr('Backend config reload requested — pin map re-pushed.','info'); } };

  calcKeysTab=()=>this.setState({ calcTab:'keys' });
  calcFxTab=()=>this.setState({ calcTab:'fx' });
  calcClear=()=>this.setState({ calc:{display:'0', acc:null, op:null, fresh:true} });
  calcBack=()=>this.setState(s=>{ const d=s.calc.display; return { calc:{...s.calc, display:d.length>1?d.slice(0,-1):'0'} }; });
  calcInput(key){
    this.setState(prev=>{
      let {display,acc,op,fresh}={...prev.calc}; const cur=()=>parseFloat(display)||0;
      if(/[0-9]/.test(key)){ display=(fresh||display==='0')?key:display+key; fresh=false; }
      else if(key==='.'){ if(fresh){display='0.';fresh=false;} else if(!display.includes('.')) display+='.'; }
      else if(key==='±'){ display=String(cur()*-1); }
      else if(key==='√'){ display=String(Math.round(Math.sqrt(Math.abs(cur()))*1e6)/1e6); fresh=true; }
      else if(key==='x²'){ display=String(Math.round(cur()*cur()*1e6)/1e6); fresh=true; }
      else if(key==='1/x'){ display=String(cur()?Math.round((1/cur())*1e6)/1e6:0); fresh=true; }
      else if(key==='='){ if(op!=null&&acc!=null){ display=String(this.calcOp(acc,cur(),op)); acc=null; op=null; fresh=true; } }
      else { if(op!=null&&acc!=null&&!fresh){ acc=this.calcOp(acc,cur(),op); display=String(acc); } else acc=cur(); op=key; fresh=true; }
      if(display.length>12) display=String(parseFloat(parseFloat(display).toPrecision(10)));
      return { calc:{display,acc,op,fresh} };
    });
  }
  calcOp(a,b,op){ const r=op==='+'?a+b:op==='−'?a-b:op==='×'?a*b:op==='÷'?(b===0?0:a/b):b; return Math.round(r*1e8)/1e8; }
  setEq(id,key){ return (e)=>{ const v=e.target.value; this.setState(s=>({ eq:{...s.eq, [id]:{...s.eq[id], [key]:v}} })); }; }

  setChatInput=(e)=>this.setState({ chatInput:e.target.value });
  chatKey=(e)=>{ if(e.key==='Enter') this.sendChat(); };

  // Where the ASK PHAGE backend (hub/chat_server.py) lives. Override with
  // window.PHAGENTIC_CHAT or ?chat=http://host:8090. The backend holds the API key.
  chatBase(){
    if(window.PHAGENTIC_CHAT) return window.PHAGENTIC_CHAT.replace(/\/$/,'');
    const o=new URLSearchParams(location.search).get('chat'); if(o) return o.replace(/\/$/,'');
    return 'http://localhost:8090';
  }

  // Compact snapshot of the live reaction state, sent with each question so the assistant
  // can ground its answer in what's happening right now.
  chatSnapshot(){
    const s=this.state;
    let source='simulation';
    if(this._ble&&this._ble.connected) source='bluetooth';
    else if(this._be&&this._be.connected) source='hub';
    return {
      source, running:!!s.running, mode:s.mode,
      t:+(+s.t).toFixed(1), phase:s.phase,
      blue:+(+s.blue).toFixed(3), amp:+(+s.amp).toFixed(3),
      halfPeriod:+(+s.halfPeriod).toFixed(1), period:+(+s.period).toFixed(1),
      cycles:s.cycles, stallRisk:+(+s.stallRisk).toFixed(2),
      stirrerPct:Math.round((s.mode==='manual'?s.stirrer:s.stirrerOut)/255*100),
      glucosePulses:s.glucosePulses, lux:s.lux, rgb:s.rgb,
    };
  }

  sendChat=(q)=>{
    const text=(typeof q==='string'?q:this.state.chatInput).trim(); if(!text) return;
    const history=this.state.chat.map(c=>({role:c.role, text:c.text}));   // before this turn
    const state=this.chatSnapshot();
    this.setState(prev=>({ chat:prev.chat.concat([{role:'user',text},{role:'sys',text:'…',streaming:true}]), chatInput:'' }));
    this.streamChat(text, history, state);
  };

  // Replace the in-flight assistant bubble's text as tokens stream in.
  _setStreamingReply(text, done){
    this.setState(prev=>{ const chat=prev.chat.slice(); const i=chat.map(c=>!!c.streaming).lastIndexOf(true); if(i>=0) chat[i]={role:'sys', text:text||(done?'':'…'), streaming:!done}; return { chat }; });
  }

  async streamChat(question, history, state){
    let acc='';
    try{
      const res=await fetch(this.chatBase()+'/chat', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({question, history, state}) });
      if(!res.ok||!res.body) throw new Error('chat backend '+res.status);
      const reader=res.body.getReader(), dec=new TextDecoder(); let buf='';
      for(;;){
        const {value,done}=await reader.read(); if(done) break;
        buf+=dec.decode(value,{stream:true});
        let nl; while((nl=buf.indexOf('\n'))>=0){
          const line=buf.slice(0,nl).trim(); buf=buf.slice(nl+1); if(!line) continue;
          let ev; try{ ev=JSON.parse(line); }catch(_){ continue; }
          if(ev.delta){ acc+=ev.delta; this._setStreamingReply(acc, false); }
          else if(ev.error){ throw new Error(ev.error); }
        }
      }
      // Empty reply (or a backend with no key) → fall back to the local responder.
      this._setStreamingReply(acc.trim()?acc:this.respond(question), true);
    }catch(e){
      // Backend unreachable (no chat server running, offline demo) → local rule-based answer.
      this._setStreamingReply(this.respond(question), true);
    }
  }

  // Minimal, safe Markdown → HTML for chat bubbles. Escapes first, then handles bold,
  // italic, inline code, links, headers, and bullet/numbered lists.
  mdEscape(s){ return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  mdInline(s){
    return s
      .replace(/`([^`]+)`/g,'<code style="background:rgba(59,55,47,.1); padding:1px 5px; border-radius:5px; font-size:.92em;">$1</code>')
      .replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')
      .replace(/__([^_]+)__/g,'<strong>$1</strong>')
      .replace(/(^|[^*])\*([^*\n]+)\*/g,'$1<em>$2</em>')
      .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,'<a href="$2" target="_blank" rel="noopener" style="color:#566e4b;">$1</a>');
  }
  mdToHtml(text){
    const lines=this.mdEscape(text).split(/\n/);
    let html='', list=null;
    const closeList=()=>{ if(list){ html+='</'+list+'>'; list=null; } };
    for(const raw of lines){
      const line=raw.trim();
      if(!line){ closeList(); continue; }
      let m;
      if((m=line.match(/^#{1,6}\s+(.*)$/))){ closeList(); html+='<div style="font-weight:600; margin:4px 0 2px;">'+this.mdInline(m[1])+'</div>'; continue; }
      if((m=line.match(/^[-*]\s+(.*)$/))){ if(list!=='ul'){ closeList(); html+='<ul style="margin:4px 0; padding-left:18px;">'; list='ul'; } html+='<li>'+this.mdInline(m[1])+'</li>'; continue; }
      if((m=line.match(/^\d+\.\s+(.*)$/))){ if(list!=='ol'){ closeList(); html+='<ol style="margin:4px 0; padding-left:20px;">'; list='ol'; } html+='<li>'+this.mdInline(m[1])+'</li>'; continue; }
      closeList(); html+='<div>'+this.mdInline(line)+'</div>';
    }
    closeList();
    return html;
  }

  respond(q){
    const s=this.state, ql=q.toLowerCase();
    if(/why|drop|decay|amplitude|weaker|small/.test(ql)) return 'Amplitude is '+Math.round(s.amp*100)+'%. It decays as glucose (reducing power) is consumed; when it stays under the threshold for two cycles the controller pulses the glucose pump to restore the swing.';
    if(/speed|fast|faster|period|slow|quick/.test(ql)){ const b=this.solve(s.targetHalfPeriod||25,'period'); return 'Half-period is '+s.halfPeriod.toFixed(1)+'s. More stirring introduces O₂ faster and shortens the blue phase — for a '+s.targetHalfPeriod+'s half-period set the stirrer near '+b.stir+' ('+Math.round(b.stir/255*100)+'%).'; }
    if(/stall|stuck|stop|risk|fail/.test(ql)) return 'Stall risk is '+Math.round(s.stallRisk*100)+'% — it climbs with time since the last colour flip (90s = stalled). If it rises, pulse glucose or raise the stirrer to re-establish the cycle.';
    if(/glucose|pump|feed|dose/.test(ql)) return 'Glucose pulses this run: '+s.glucosePulses+' ('+s.glucoseDoseMs+'ms each). Each bolus replenishes reducing power; the auto trigger fires when amplitude drops below '+s.ampThreshold+'%.';
    if(/blue|colou?r|sensor|reading/.test(ql)) return 'Live blue intensity is '+s.blue.toFixed(2)+' ('+s.phase+' phase), read from the TCS34725 as (b−r) and normalized. The waveform you see is that signal over time.';
    if(/stir|o2|oxygen|mix/.test(ql)) return 'Stirrer is at '+Math.round(s.stirrerOut/255*100)+'%. It sets the O₂ introduction rate — the primary knob for shaping oscillation period and amplitude.';
    return 'I read the live colour sensor and the oscillation estimate. Ask me about amplitude, period/speed, stalling, glucose dosing, or the stirrer.';
  }

  renderVals(){
    const s=this.state, pad=n=>String(n).padStart(2,'0');
    const palettes={ Meadow:['rgba(120,140,108,.4)','rgba(150,140,180,.34)','rgba(200,170,110,.36)','rgba(122,140,156,.34)'], Clay:['rgba(196,128,96,.4)','rgba(206,150,96,.36)','rgba(176,140,96,.34)','rgba(160,120,140,.32)'], Mist:['rgba(122,140,156,.4)','rgba(150,140,180,.36)','rgba(120,140,108,.32)','rgba(150,160,150,.3)'] };
    const pal=palettes[this.props.palette]||palettes.Meadow;
    // Oscillation waveform: blue intensity over the recent history, index-mapped to width.
    const Hh=s.hist, n=Hh.length, X=i=>n>1?(i/(n-1))*680:0, Y=v=>196-Math.max(0,Math.min(1,v))*178;
    // Two traces: basePath = raw observed blue (muted), ourPath = backend's
    // EMA-cleaned estimate (bold). Older history pre-estimate falls back to raw.
    let ourPath,basePath;
    if(this._pc&&this._pc.hist===Hh){ ourPath=this._pc.o; basePath=this._pc.b; } else { ourPath=n?Hh.map((p,i)=>(i?'L':'M')+X(i).toFixed(1)+' '+Y(p.blueEst!=null?p.blueEst:p.blue).toFixed(1)).join(' '):''; basePath=n?Hh.map((p,i)=>(i?'L':'M')+X(i).toFixed(1)+' '+Y(p.blue).toFixed(1)).join(' '):''; this._pc={hist:Hh,o:ourPath,b:basePath}; }
    const kindColor={ info:'#2e2b24', dim:'rgba(46,43,36,.55)', warn:'#94762f', win:'#566e4b' };
    const narrFeed=s.narr.slice().reverse().map((m,i)=>({ txt:m.txt, color:kindColor[m.kind]||'#2e2b24', size:i===0?'14.5px':'13px', weight:i===0?'500':'400' }));
    const chatMsgs=s.chat.map(c=>{
      const html=c.role==='user' ? this.mdEscape(c.text).replace(/\n/g,'<br>') : this.mdToHtml(c.text);
      return { align:c.role==='user'?'flex-end':'flex-start', bg:c.role==='user'?'#6f8466':'rgba(255,255,255,.55)', color:c.role==='user'?'#fbf8f2':'#2e2b24', mref:(el)=>{ if(el) el.innerHTML=html; } };
    });
    const stall=s.stallRisk, stallCol=stall<0.5?'#94762f':stall<0.8?'#b06a45':'#9c4a3c';
    const active=(s.drag&&s.drag.id)||(s.resize&&s.resize.id); const pf={};
    for(const id in s.panels){ const p=s.panels[id]; const live=(active===id); pf[id]={ tf:`translate3d(${p.x.toFixed(1)}px,${p.y.toFixed(1)}px,0)`, z:(p.zi||1)+(live?1000:0), w:p.w+'px', h:p.h+'px', open:p.open, title:this.labels[id], resize:this.resizeH[id], trans:live?'none':'transform .5s cubic-bezier(.4,0,.2,1), width .5s cubic-bezier(.4,0,.2,1), height .5s cubic-bezier(.4,0,.2,1)' }; }
    const dockTabs=this.panelIds.filter(id=>s.panels[id] && !s.panels[id].open).map(id=>({ id, label:this.labels[id], h:this.openH[id] }));
    const contentHpx=this.deskContentH(s.panels);
    const pr=this.predict(s.mode==='manual'?s.stirrer:s.stirrerOut);
    const sol=this.solve(s.targetHalfPeriod,s.solveMode);
    const solveTxt='target '+s.targetHalfPeriod+'s → stirrer '+sol.stir+' ('+Math.round(sol.stir/255*100)+'%), amp ~'+Math.round(sol.amp*100)+'%';
    const predHzColor=stallCol;
    const ang=(val,min,max)=>(((val-min)/(max-min))*270-135).toFixed(0)+'deg';
    // equation library list + selected-equation detail
    const eqList=this.eqLib.map(d=>({ name:d.name, expr:d.expr, sel:()=>this.selectEq(d.id) }));
    const eqSelDef=this.eqLib.find(d=>d.id===s.eqSel)||null;
    let eqDetail={ name:'', expr:'', desc:'', fields:[], result:'—', unit:'', clear:()=>{}, conv:false, normal:false, phage:false, tempC:'', tempF:'', phageS:0, phageSStr:'', phageCount:'', phageSwatch:'rgb(255,255,255)', phageRgb:'', phagePretty:'—' };
    if(eqSelDef){
      const bag=s.eq[eqSelDef.id]||{};
      if(eqSelDef.phageConv){ const sStr=bag.s??'', pStr=bag.p??''; const sn=parseFloat(sStr); const Scur=isNaN(sn)?0:Math.max(0,Math.min(10,sn)); const rgb=this.sliderToRgb(Scur);
        eqDetail={ name:eqSelDef.name, expr:eqSelDef.expr, desc:eqSelDef.desc, conv:false, normal:false, phage:true, fields:[], result:'', unit:'', clear:()=>this.clearEq(eqSelDef.id), tempC:'', tempF:'',
          phageS:Scur, phageSStr:sStr, phageCount:pStr, phageSwatch:'rgb('+rgb.join(',')+')', phageRgb:'R '+rgb[0]+'  G '+rgb[1]+'  B '+rgb[2], phagePretty:(sStr===''||isNaN(sn))?'—':this.fmtPhagePretty(this.sliderToPhage(Scur)) }; }
      else if(eqSelDef.converter){ eqDetail={ name:eqSelDef.name, expr:eqSelDef.expr, desc:eqSelDef.desc, conv:true, normal:false, phage:false, fields:[], result:'', unit:'', clear:()=>this.clearEq(eqSelDef.id), tempC:(s.eq.temp&&s.eq.temp.c)||'', tempF:(s.eq.temp&&s.eq.temp.f)||'' }; }
      else { const v={}; let ok=true; eqSelDef.fields.forEach(([lab,key])=>{ const raw=bag[key]; const num=parseFloat(raw); v[key]=isNaN(num)?0:num; if(raw===undefined||raw==='') ok=false; }); const res=ok?eqSelDef.fn(v):null;
        eqDetail={ name:eqSelDef.name, expr:eqSelDef.expr, desc:eqSelDef.desc, conv:false, normal:true, phage:false, clear:()=>this.clearEq(eqSelDef.id), tempC:'', tempF:'',
          fields:eqSelDef.fields.map(([label,key,unit])=>({ label, unit:unit||'', val:bag[key]??'', h:this.setEq(eqSelDef.id,key) })),
          result: res==null?'—':Number(res.toFixed(eqSelDef.dp)).toLocaleString(), unit: res==null?'':eqSelDef.unit };
      }
    }
    // colour capture log
    const capturesList=s.captures.map((c,i)=>({ color:c.color, blueTxt:c.blue+'%', metaTxt:'amp '+c.amp+'% · '+c.period+'s · '+c.phase+' · cyc '+c.cycles, subTxt:'stir '+c.stirrer+'% · t '+c.t+'s · run '+pad(c.run), rgbTxt:'R'+c.rgb[0]+' G'+c.rgb[1]+' B'+c.rgb[2], selBg:s.compareSel.indexOf(i)>=0?'rgba(86,110,75,.22)':'rgba(255,255,255,.32)', selBorder:s.compareSel.indexOf(i)>=0?'#566e4b':'rgba(59,55,47,.12)', pick:()=>this.toggleCompareSel(i) }));
    const compareList=s.compareSel.map(i=>s.captures[i]).filter(Boolean).map(c=>({ color:c.color, blueTxt:c.blue+'%', l1:'amp '+c.amp+'%', l2:c.period+'s', l3:c.phase, l4:'cyc '+c.cycles, l5:'stir '+c.stirrer+'%' }));
    // home-screen floating phages — drift physics only. The spin3d animation
    // supplies the 3D feel; we deliberately don't add a mouse-driven tilt (its
    // extreme rotateX near the top edge re-rasterized the layer and flickered).
    const landingBodies=s.bodies.map(o=>({ id:o.id, tf:`translate3d(${o.x.toFixed(1)}px,${o.y.toFixed(1)}px,0) scale(${o.scale})`, spinS:o.spin+'s', op:(o.kind==='full'?1:0.55).toFixed(2) }));
    const runsList=s.runs.slice().reverse().map((r)=>{ const realIdx=s.runs.indexOf(r); return { label:(r.name||('Run '+pad(r.n))), color:r.color, sub:r.cycles+' cyc', del:()=>this.deleteRun(realIdx) }; });
    const runsEmpty=s.runs.length===0;
    return {
      watchRace:this.watchRace, goHome:this.goHome,
      phageFaces:this.phage.faces, phageLines:this.phage.lines, phageFibers:this.phage.fibers, phageDots:this.phage.dots, bpT:this.phage.bpT, bpRingW:this.phage.rS.toFixed(1)+'px',
      landingBodies, landingRef:this.landingRef, onLandingMove:this.onLandingMove,
      sensorRgbTxt:'R '+s.rgb[0]+'  G '+s.rgb[1]+'  B '+s.rgb[2], sensorLux:String(s.lux),
      landingOpacity:s.onLanding?'1':'0', landingPE:s.onLanding?'auto':'none', landingTransform:s.onLanding?'scale(1)':'scale(1.05)',
      consoleOpacity:s.onLanding?'0':'1', consolePE:s.onLanding?'none':'auto', enter:this.enter, shineMove:this.shineMove, shineReset:this.shineReset, gshineMove:this.gshineMove, gshineReset:this.gshineReset, logoLeave:this.logoLeave,
      wcOpacity:String(this.props.watercolor??0.85), blobA:pal[0], blobB:pal[1], blobC:pal[2], blobD:pal[3],
      scrollRef:this.scrollRef, stageTransform:s.uiZoom===1?'none':'scale('+s.uiZoom+')', spacerW:(s.stageW*s.uiZoom).toFixed(0)+'px', spacerH:(contentHpx*s.uiZoom).toFixed(0)+'px', stageWpx:s.stageW.toFixed(0)+'px', stageHpx:contentHpx.toFixed(0)+'px',
      zoomTxt:Math.round(s.uiZoom*100)+'%', zoomIn:this.zoomIn, zoomOut:this.zoomOut, zoomReset:this.zoomReset, tidyDesk:this.tidyDesk,
      toggleRun:this.toggleRun, remelt:this.remelt, bump:this.bump, manualFire:this.manualFire,
      runLabel:s.running?'PAUSE':'RUN', runLabel2:'RUN '+pad(s.runIndex), runIcon:s.running?'‖':'►',
      statusTxt:s.running?'LIVE':'PAUSED', statusDot:s.running?'#6f8466':'#94762f', clockTxt:s.t.toFixed(1)+'s',
      sourceTxt:s.source==='hub'?'⌁ CONNECTED':'◌ OFFLINE', sourceColor:s.source==='hub'?'#566e4b':'rgba(46,43,36,.45)',
      isAuto:s.mode==='auto', isManual:s.mode==='manual',
      targetBlueVal:Math.round(s.targetBlue*100), targetBlueFill:(s.targetBlue*100).toFixed(0)+'%', setTargetBlue:this.setTargetBlue, targetTimeVal:s.targetTime, setTargetTime:this.setTargetTime,
      targetBlueSwatch:'rgb('+this.rgbForBlue(s.targetBlue).join(',')+')',
      targetPhageVal:s.targetPhage, setTargetPhage:this.setTargetPhage, targetPhagePretty:this.fmtPhagePretty(this.sliderToPhage(s.targetBlue*10)),
      bleConnect:this.bleConnect, bleLabel:s.live?'⌁ connected':'⌁ connect', bleBg:s.live?'rgba(86,110,75,.18)':'rgba(111,132,102,.12)', bleColor:'#566e4b',
      openSettings:this.openSettings, closeSettings:this.closeSettings, settingsOpen:s.settingsOpen,
      bleName:s.bleName, setBleName:this.setBleName, bleReconnect:this.bleReconnect, bleDisconnect:this.bleDisconnect,
      bleConnected:s.source==='hub', bleStateTxt:(s.source==='hub'?'connected':'offline'), bleKnownTxt:(this._be?this._be.url:''),
      bleSupTxt:'',
      panels:pf, dragH:this.dragH, closeH:this.closeH, stopProp:(e)=>e.stopPropagation(), dockTabs,
      animTrans:s.animating?'transform .5s cubic-bezier(.4,0,.2,1), width .5s cubic-bezier(.4,0,.2,1), height .5s cubic-bezier(.4,0,.2,1)':'none',
      vesselColor:'rgb('+s.rgb.join(',')+')',
      captureColor:this.captureColor, clearCaptures:this.clearCaptures, toggleCompare:this.toggleCompare, compareMode:s.compareMode, capturesList, compareList,
      captureCountTxt:s.captures.length?(s.captures.length+' saved'):'none saved', compareBtnTxt:s.compareMode?'done':'compare',
      eqList, eqLibMode:(s.calcTab==='fx'&&!s.eqSel), eqDetailMode:(s.calcTab==='fx'&&!!s.eqSel),
      eqName:eqDetail.name, eqExpr:eqDetail.expr, eqDesc:eqDetail.desc, eqFields:eqDetail.fields, eqResult:eqDetail.result, eqUnit:eqDetail.unit, eqClear:eqDetail.clear, eqConv:eqDetail.conv, eqNormal:eqDetail.normal, eqTempC:eqDetail.tempC, eqTempF:eqDetail.tempF, setTempC:this.setTempC, setTempF:this.setTempF, eqBack:this.eqBack,
      eqPhage:eqDetail.phage, phageSliderVal:eqDetail.phageS, phageSliderStr:eqDetail.phageSStr, phageCountVal:eqDetail.phageCount, phageSwatch:eqDetail.phageSwatch, phageRgbTxt:eqDetail.phageRgb, phagePrettyTxt:eqDetail.phagePretty, setPhageSlider:this.setPhageSlider, setPhageCount:this.setPhageCount,
      tempOursTxt:Math.round(s.blue*100)+'%', tempCleanTxt:Math.round((s.blueEst!=null?s.blueEst:s.blue)*100)+'%', tempBaseTxt:Math.round(s.amp*100)+'%', oursSolidTxt:s.phase.toUpperCase(), baseSolidTxt:'tgt '+s.ampThreshold+'%',
      oursCryst:s.blue.toFixed(2), baseCryst:s.amp.toFixed(2), oursGlow:s.glucoseActive?'0 0 34px rgba(148,118,47,.55)':'0 0 6px rgba(95,115,85,0)',
      turbidity:s.blue.toFixed(2), turbidityTxt:s.blue.toFixed(2),
      ourPath, basePath, baseFired:false, oursFired:false,
      baseMarkX:'-10', oursMarkX:'-10',
      superPct:Math.round((s.ampEst||0)*100), superW:((s.ampEst||0)*100).toFixed(0)+'%', obsAmpPct:Math.round(s.amp*100), titerTxt:s.halfPeriod.toFixed(1)+'s',
      telemetry:[{k:'BLUE · obs', v:Math.round(s.blue*100)+'%', c:'rgba(46,43,36,.55)'},{k:'BLUE · est', v:Math.round((s.blueEst!=null?s.blueEst:s.blue)*100)+'%', c:'#566e4b'},{k:'PHASE', v:(s.phaseEst||s.phase)==='blue'?'BLUE':'COLORLESS', c:'#2e2b24'},{k:'CYCLES', v:String(s.cycles), c:'#2e2b24'}],
      rewardTxt:String(s.cycles), lastYieldTxt:s.period?('~'+s.period.toFixed(0)+'s'):'—', narrFeed,
      autoSegBg:s.mode==='auto'?'#6f8466':'transparent', autoSegColor:s.mode==='auto'?'#fbf8f2':'rgba(46,43,36,.7)', manSegBg:s.mode==='manual'?'#94762f':'transparent', manSegColor:s.mode==='manual'?'#fbf8f2':'rgba(46,43,36,.7)',
      setAuto:this.setAuto, setManual:this.setManual, startCycling:this.startCycling, knobsOpacity:s.mode==='manual'?'1':'.5',
      knobCool:this.knobCool, knobMoi:this.knobMoi, knobThr:this.knobThr, knobLight:this.knobLight,
      // read-only actuator status (ACTUATORS panel) — shows what the model is doing
      actPolicyTxt:s.mode==='auto'?'AUTO · model driving':'MANUAL · you driving', actPolicyColor:s.mode==='auto'?'#566e4b':'#94762f',
      actStirPct:Math.round(s.stirrerOut/255*100)+'%', actStirW:(s.stirrerOut/255*100).toFixed(0)+'%',
      actStirLevel:s.stirrerOut<45?'OFF':s.stirrerOut<125?'LOW':s.stirrerOut<207?'MID':'HIGH',
      actLightPct:Math.round((s.lightOut||0)/255*100)+'%', actLightW:((s.lightOut||0)/255*100).toFixed(0)+'%',
      actGluTxt:s.glucoseActive?'ON':'OFF', actGluColor:s.glucoseActive?'#fbf8f2':'rgba(46,43,36,.5)', actGluBg:s.glucoseActive?'#5f7fb0':'rgba(59,55,47,.1)',
      actNaohTxt:s.naohActive?'ON':'OFF', actNaohColor:s.naohActive?'#fbf8f2':'rgba(46,43,36,.5)', actNaohBg:s.naohActive?'#94762f':'rgba(59,55,47,.1)',
      actGluPulses:String(s.glucosePulses||0),
      stirFill:(s.stirrer/255*100).toFixed(0)+'%', gluFill:((s.glucoseDoseMs-50)/1950*100).toFixed(0)+'%', ampFill:((s.ampThreshold-5)/90*100).toFixed(0)+'%', lightFill:(s.light/255*100).toFixed(0)+'%',
      manualOn:s.mode==='manual',
      gluSetOn:this.gluSetOn, gluSetOff:this.gluSetOff, pulseGlucose:this.pulseGlucose, naohSetOn:this.naohSetOn, naohSetOff:this.naohSetOff,
      gluOnBg:s.glucoseOn?'#5f7fb0':'transparent', gluOnColor:s.glucoseOn?'#fff':'rgba(46,43,36,.55)', gluOffBg:s.glucoseOn?'transparent':'rgba(59,55,47,.14)', gluOffColor:s.glucoseOn?'rgba(46,43,36,.55)':'#2e2b24', gluDot:s.glucoseActive?'#5f7fb0':'rgba(46,43,36,.2)',
      naohOnBg:s.naohOn?'#94762f':'transparent', naohOnColor:s.naohOn?'#fff':'rgba(46,43,36,.55)', naohOffBg:s.naohOn?'transparent':'rgba(59,55,47,.14)', naohOffColor:s.naohOn?'rgba(46,43,36,.55)':'#2e2b24', naohDot:s.naohActive?'#94762f':'rgba(46,43,36,.2)',
      stirSetOn:this.stirSetOn, stirSetOff:this.stirSetOff, lightSetOn:this.lightSetOn, lightSetOff:this.lightSetOff,
      gluToggle:this.gluToggle, naohToggle:this.naohToggle, gluStateTxt:s.glucoseOn?'ON':'OFF', naohStateTxt:s.naohOn?'ON':'OFF',
      gluBtnBg:s.glucoseOn?'linear-gradient(180deg,#7aa0d8,#5f7fb0)':'linear-gradient(180deg, rgba(255,255,255,.5), rgba(224,216,200,.28))', gluBtnColor:s.glucoseOn?'#fff':'rgba(46,43,36,.7)', gluBtnGlow:s.glucoseOn?'0 0 20px rgba(95,127,176,.6), inset 0 2px 6px rgba(255,255,255,.45)':'inset 0 2px 6px rgba(255,255,255,.7)',
      naohBtnBg:s.naohOn?'linear-gradient(180deg,#c8a24e,#94762f)':'linear-gradient(180deg, rgba(255,255,255,.5), rgba(224,216,200,.28))', naohBtnColor:s.naohOn?'#fff':'rgba(46,43,36,.7)', naohBtnGlow:s.naohOn?'0 0 20px rgba(148,118,47,.55), inset 0 2px 6px rgba(255,255,255,.45)':'inset 0 2px 6px rgba(255,255,255,.7)',
      stirOnBg:s.stirrer>0?'#5f7fb0':'transparent', stirOnColor:s.stirrer>0?'#fff':'rgba(46,43,36,.55)', stirOffBg:s.stirrer>0?'transparent':'rgba(59,55,47,.14)', stirOffColor:s.stirrer>0?'rgba(46,43,36,.55)':'#2e2b24',
      lightOnBg:s.light>0?'#b9923a':'transparent', lightOnColor:s.light>0?'#fff':'rgba(46,43,36,.55)', lightOffBg:s.light>0?'transparent':'rgba(59,55,47,.14)', lightOffColor:s.light>0?'rgba(46,43,36,.55)':'#2e2b24',
      stirName:this._names.stirrer, gluName:this._names.glucose, naohName:this._names.naoh, lightName:this._names.light,
      stirPinTxt:'GPIO '+this._pins.stirrer, gluPinTxt:'GPIO '+this._pins.glucose, naohPinTxt:'GPIO '+this._pins.naoh, lightPinTxt:'GPIO '+this._pins.light,
      coolVal:Math.round(s.stirrer), moiVal:Math.round(s.glucoseDoseMs), thrVal:Math.round(s.ampThreshold), setCool:this.setCool, setMoi:this.setMoi, setThr:this.setThr,
      predFireTxt:pr.halfP.toFixed(1)+'s', predSolidTxt:Math.round(pr.amp*100)+'%', predYTxt:pr.period.toFixed(1)+'s', predHzTxt:Math.round(s.stallRisk*100)+'%', predHzColor,
      targetVal:s.targetHalfPeriod, setTarget:this.setTarget, solveMode:s.solveMode, setSolveEq:this.setSolveEq, setSolveEnergy:this.setSolveEnergy,
      solveEqBg:s.solveMode==='period'?'#6f8466':'transparent', solveEqColor:s.solveMode==='period'?'#fbf8f2':'rgba(46,43,36,.7)', solveEnBg:s.solveMode==='stir'?'#6f8466':'transparent', solveEnColor:s.solveMode==='stir'?'#fbf8f2':'rgba(46,43,36,.7)',
      solveTxt, applySolve:this.applySolve,
      pulseNaoh:this.pulseNaoh, naohBg:s.naohActive?'#94762f':'transparent', naohColor:s.naohActive?'#fbf8f2':'#94762f',
      lightVal:Math.round(s.light), lightPct:Math.round(s.light/255*100)+'%', setLight:this.setLight,
      recalibrateSensor:this.recalibrateSensor, reloadCfg:this.reloadCfg, calibTxt:s.calibTxt,
      calcDisplay:s.calc.display, calcKeys:this.calcKeys, calcKeysMode:s.calcTab==='keys', calcFxMode:s.calcTab==='fx', calcKeysTab:this.calcKeysTab, calcFxTab:this.calcFxTab, calcClear:this.calcClear, calcBack:this.calcBack,
      calcKeysColor:s.calcTab==='keys'?'#2e2b24':'rgba(46,43,36,.4)', calcFxColor:s.calcTab==='fx'?'#2e2b24':'rgba(46,43,36,.4)',
      chatMsgs, chatInput:s.chatInput, setChatInput:this.setChatInput, chatKey:this.chatKey, sendChat:this.sendChat, chatRef:this.chatRef,
      runsList, runsEmpty, addRun:this.addRun,
      noteTabs:s.notes.map((n,i)=>({ title:(n.title||('Note '+(i+1))), sel:this.selectNote(i), del:this.deleteNote(i), bg:i===s.noteIdx?'rgba(111,132,102,.18)':'rgba(255,255,255,.34)', color:i===s.noteIdx?'#2e2b24':'rgba(46,43,36,.6)', border:i===s.noteIdx?'#6f8466':'rgba(59,55,47,.14)' })),
      noteTitle:(s.notes[s.noteIdx]||{}).title||'', noteBody:(s.notes[s.noteIdx]||{}).body||'', setNoteTitle:this.setNoteTitle, setNoteBody:this.setNoteBody, newNote:this.newNote,
      runNameTxt:s.runName, runColorVal:s.runColor, setRunName:this.setRunName, openColor:this.openColor, colorOpen:s.colorOpen,
      colorSwatches:this.runPalette.concat(this.huePalette).map(hex=>({ hex, pick:()=>this.pickRunColor(hex) })),
      glowColor:this.hexToRgba(s.runColor,0.12), glowColor2:this.hexToRgba(s.runColor,0.04),
      hint:s.hint, hintOpacity:s.hint?'1':'0', clearHint:this.clearHint, hintLeft:s.hintX.toFixed(0)+'px', hintTop:s.hintY.toFixed(0)+'px',
      hConnect:this.setHint('Connect to the bioreactor over Bluetooth (Web Bluetooth)'), hTidy:this.setHint('Re-pack every panel neatly into the workspace'), hPause:this.setHint(s.running?'Pause the control loop':'Resume the control loop'), hRestart:this.setHint('Log this run and start a fresh one'), hDisturb:this.setHint('Inject a disturbance to test the controller'), hPulse:this.setHint('Manually pulse the glucose pump'), hSettings:this.setHint('Bluetooth & settings'), hHome:this.setHint('Back to the home page'),
    };
  }
};
};
